# Generated by Django 3.0.6 on 2020-07-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskApp',
        ),
    ]
